name: Build mpv

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build snap
        id: snapcraft
        uses: snapcore/action-build@v1
        with:
          path: mpv
  
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: mpv-snap
          path: ${{ steps.snapcraft.outputs.snap }}
