name: Build SMPlayer

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build snap
        id: snapcraft
        uses: snapcore/action-build@v1
        with:
          path: smplayer/core22
  
      - name: Create artifact
        #if: ${{false}}
        uses: actions/upload-artifact@v2
        with:
          name: smplayer-snap
          path: ${{ steps.snapcraft.outputs.snap }}

      - name: Publish
        if: ${{false}}
        uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{steps.snapcraft.outputs.snap }}
          release: edge
